### PR TITLE
Blog example

### PR DESCRIPTION
**Pull request by bevennyamande**
Fixes #

## Proposed changes

- blog app tutorial 
- 
-

### CODE REVIEW

**Comment by florimondmanca** [comment]
Hi @bevennyamande. I think we should discuss which tutorial you'd like to work on and what you're planning to write up on #25 first. I'll clarify there (and in `CONTRIBUTING.md`) how one should process before submitting a PR. :)

**Comment by bevennyamande** [comment]
A blog to demonstrate CRUD operations as well as integration with sqlite3 db

**Comment by florimondmanca** [comment]
@bevennyamande So the idea is to create a few template-rendered web pages to list, read, create and delete blog posts, right? If so, that sounds good to me.

I can create a separate repo for that (as I've done for Tarantula, the web spider) and give you write access, so you can host the code there  — I'm planning on removing the `example` app in here when the tutorials are done. What do you think? The tutorial contents will still need to be hosted here, in the `docs/` directory.

**Comment by bevennyamande** [comment]
OK yes its a great idea will be glad to contribute

**Comment by florimondmanca** [comment]
@bevennyamande Done — I created [bloguero](../../bloguero) (suggested name!) and you should have received an invite link for write access.

As has already been discussed in #4, since Bocadillo is async you should demonstrate using an asynchronous SQLite client, e.g. [aiosqlite](https://github.com/jreese/aiosqlite). Otherwise, calls to the `sqlite3` will block and the whole purpose of Bocadillo as an async framework is lost. :)

I'm closing this since I suppose you'll be working on the Bloguero repo before writing up the tutorial. Feel free to reopen a PR for the tutorial in the future!

Would be great if we have the blog tutorial ready within 2-3 weeks from now. I'll be glad to help you out with Bloguero — code reviews, questions, usage of Bocadillo, etc. Ping me on Twitter if needed! :)

Thanks!

**Comment by bevennyamande** [comment]
I will ping when necessary

**Pull request closed without merging**
