### PR TITLE
Add route hooks

### LINKED ISSUE #15: Add route hooks
As a developer, I'd find it very useful if there was a way to intercept the routing mechanism and execute code *before* or *after* a specific view is executed.

This is different from [RoutingMiddleware] because such **hooks** would be applied on a per-route basis, e.g.:

```python
def do_something(req, res, view, params):
    pass

@api.before(do_something)
@api.route('/')
async def index(req, res):
    pass

@api.route('/')
class IndexView:

    @api.before(do_something)
    async def get(self, req, res):
        pass
```

In order to have a basic level of reusability, it should be possible to pass extra args or kwargs to hooks, e.g.:

```python
def check_for_header(req, res, view, params, header):
    assert header in req.headers

@api.before(check_for_header, header='x-my-header')
@api.route('/')
async def index(req, res):
    pass
```

### PR DESCRIPTION
**Pull request by florimondmanca**
- Refactor the view layer to facilitate addition of hooks.
- Implement registration of hooks executed just before or just after a view is executed.

Fixes #15

### CODE REVIEW

**Comment by alin23** [comment]
Hi @florimondmanca ! Bocadillo looks like a great project and I've already started using it in two of my projects!
This hooks feature would be really useful, but I think it would be even more useful if the hooks would be allowed to be `async`.

A few use cases I could think of:
* Validating the request body using `jsonschema` or `marshmallow`
* Checking for authentication or other things that require accessing a database using async layers (for example I use `asyncpg` to check the database and this would not be possible in a sync hook)

The hook doesn't have to always be async, but it can be allowed to be using `iscoroutine`.
The same could be applied to the middleware `on_before_dispatch` and `on_after_dispatch` methods since they are called inside an `async` function.

What do you think?

**Comment by florimondmanca** [comment]
Hi @alin23, very good points about async support for these hooks (and middleware!). As it is now, hooks won't allow to read the request body because it can only be through `await req.body`, `await req.json()`, etc.

The support of both async and sync functions becomes a recurring problem in the code base, I'd also like to find a more generic (yet efficient) way of dealing with it.

As for your point concerning database calls — I've just added #4 about support for databases and an ORM within Bocadillo. You seem to have valuable input concerning databases in an async context, so feel free to check out the issue. :-)

I'll mark these as needing revision and come back to it soon.

**Comment by alin23** [comment]
Oh man, finally an ORM that uses `asyncpg` behind! I wish `tortoise` existed half a year ago when I had to convert all the db interactions in [Noiseblend](https://www.noiseblend.com) to `async`.

Yes, #4 would also be a great addition if tortoise would be considered instead of orator. A sync ORM is almost impossible to use in the context of an async/single-thread framework because every database call would halt every request handling until the call finishes. Of course, the db calls can be made in separate threads but as you probably know, Python doesn't have real parallelization when it comes to threads.

Anyway, the db point was just one of many examples. I could think of others like caching with `aioredis` or collecting metrics using `aioinflux` etc. The point is that with such a simple change, the hooks and middlewares would become infinitely more useful ^_^

I forked your repo and made some preliminary changes for the hooks here: https://github.com/alin23/bocadillo/commit/66b3bb00270b5e38a3fb6941c56b9f98ac28b7f3#diff-17d3d0ba7be943aecedec66175af840c

**Comment by alin23** [comment]
By the way, I have yet to find an elegant way to merge sync and async codebases. Most of the time I had to split a whole project in 2 separate sync and async codebases to keep the code readable. Let me know if you think of a better solution.

**Comment by florimondmanca** [comment]
@alin23 Thanks for the tip about the reusable sync -> async converter :) I used it to add support for async hooks. Async middleware will be implemented in a future PR (this is a separate issue).

Note that, although it was already written that way in the docs, I removed the `view` parameter from hooks because we can't provide a uniform view object/function (views undergo a lot of wrapping between the moment they're declared and the moment they're available to hooks).

If you have any comments, feel free. :) I'll probably merge this tonight.

**Pull request merged**
